# -*- coding: utf-8 -*-
"""working_with_Image_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9MX2A5tewjGy7Ao2uOVvUUcTbefxvoV

## **Working with Image**
"""

# If you use local computer, you need to install pip and PIL or PILLOW
# Depends on your OS, instruction is vary. Get some help from internet search!
import PIL
print (PIL.PILLOW_VERSION)

"""Let's read an image from a website!
The following code makes be ready to use url and files in your Google Drive.
"""

import urllib.request
import io, sys
from PIL import Image

# with your local computer, you don't need the following two lines
# from google.colab import drive
# drive.mount('/content/drive')
# 
"""Now, let's open two images: one from online and one from local drive."""

# Get an image from website
URL = 'https://tjhsst.fcps.edu/sites/default/files/TJ%20LogoTransparent.png'
f = io.BytesIO(urllib.request.urlopen(URL).read())
img = Image.open(f)

# In your local machine, you can type: img.show() instead of saving and checking it.
# img.save('drive/My Drive/Colab Notebooks/url_logo.png', 'PNG')
img.show()

# Get an image from local or Google drive.
# fn = 'drive/My Drive/Colab Notebooks/tj_logo.jpg'
fn = 'tj_logo.jpg'
img2 = Image.open(fn)
#img2.save('drive/My Drive/Colab Notebooks/tj_logo2.png', 'PNG')
img2.show()

"""Let's assume that you do not know what is the user input for the file. A user may type a url or a file name. Let's check at once!"""

import os
file = input("Type a image url or file name: ")
if not os.path.isfile(file):
  file = io.BytesIO(urllib.request.urlopen(file).read())
img3 = Image.open(file)
print (img.size)